/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include"main.h"

int main(void)
{
	RCC_AHB1ENR_t *p_rcc = (RCC_AHB1ENR_t*)(0x40023830);
	GPIOx_MODER_t *p_gpioa = (GPIOx_MODER_t*)(0x40020000);
	GPIOx_ODR_t *p_gpioa_odr = (GPIOx_ODR_t*)(0x40020014);

	long long int delay = 100000;

	p_rcc->gpioa_en = 1;

	p_gpioa->moder5 = 01;


    /* Loop forever */
	while(1)
		{
			//Setting O/P data reg for GPIO A pin A5 to which LED is connected
				p_gpioa_odr->odr5 = 1;
				while(delay > 0) { delay--; }
				//Setting O/P data reg for GPIO A pin A5 to which LED is connected
				p_gpioa_odr->odr5 = 0;
				while(delay < 100000) { delay++; }
		}
}
