/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*
 * ledon.c
 *
 *  Created on: Nov 1, 2020
 *      Author: KIIT
 */
#include<stdint.h>
//gpioA =0x4002 0000
//0x04
//pointer declaration  for RCC, GPIO mode and OP data register


int main(void)
{
	//pointer declaration for RCC, GPIO A mode and OP DATA register
	uint32_t* pRCC_en = (uint32_t*)0x40023830 ;
	uint32_t* pGPIOAmode = (uint32_t*)0x40020000 ;
	uint32_t* pOPDataReg = (uint32_t*)0x40020014 ;
	long long int delay = 100000;

//Enabling Clock(RCC) for GPIO A
	*pRCC_en |= 1;

//Clearing GPIO A mode5
	*pGPIOAmode &= ~(3 << 10);

//Setting GPIO A mode5 to 01 to set it to o/p type
	*pGPIOAmode |= (1 << 10);

    /* Loop forever */
	while(1)
	{
		//Setting O/P data reg for GPIO A pin A5 to which LED is connected
			*pOPDataReg |= 1 << 5;
			while(delay > 0) { delay--; }
			//Setting O/P data reg for GPIO A pin A5 to which LED is connected
			*pOPDataReg &= ~(1 << 5);
			while(delay < 100000) { delay++; }
	}
}
